### ISSUE TITLE
Unable to close interface or operate if open transferinfo interface in sailing mode

### ISSUE THREAD

**Issue by NathanIceSea** [smallp/DSPTransferInfo#2]
As mentioned, After pressing F4 while sailing (Tab not pressed), all operations got stuck, and Tab or F4 does not help

航行模式且指针没有分离的情况下，按下 F4 打开界面后无法关闭界面或操作

**Comment by NathanIceSea** [comment]
另外目前的搜索功能只能搜索站点名称，但是又无法批量地命名站点，这一点如果能改进批量命名或增加条件搜索的话是最好了

**Comment by smallp** [comment]
航行模式的bug已知，目前注意一下可以避免，下个版本会改。
搜索功能我考虑允许搜索物品，这样应该可以满足需求。至于批量命名……感觉用处不大，一般只会用关键的几个物流站，有了搜索物品功能就行了。

**Comment by smallp** [comment]
搜索功能已优化。航行模式无法解锁鼠标，所以我禁用了。
