### ISSUE TITLE
Version 1.1.3 seems to be unable to search for items and can only search for logistics stations?

### ISSUE THREAD

**Issue by ZSK5418** [smallp/DSPTransferInfo#3]
Version 1.1.3 seems to be unable to search for items and can only search for logistics stations?
Unable to search for items, only logistics stations can be searched. Please have the author test it。

**Comment by smallp** [comment]
Got it. I'll see soon.

**Comment by smallp** [comment]
Done. See the latest version.

**Comment by jvmirdel** [comment]
Be nice if search was case insensitive
