### ISSUE TITLE
【功能请求】是否可以增加一个隐藏/显示采集器的开关？是否可以显示星球名称？

### ISSUE THREAD

**Issue by jessefjxm** [smallp/DSPTransferInfo#4]
大佬，最近的更新增加了采集器的显示后，有些占位置，能否增加一个开关隐藏采集器？
另外，目前列表里没有显示物流塔在哪一颗星球，有时候不方便定位，能否加上这一个信息呢？

**Comment by smallp** [comment]
好！下个版本安排

**Comment by smallp** [comment]
搞定，你可以在 release 下到最新的。
