### ISSUE TITLE
Game crash when fetching Items, with mid game number of stations

### ISSUE THREAD

**Issue by jvmirdel** [smallp/DSPTransferInfo#5]
First crash happened when undoing a built.

Seems to take a while to load station list and display items, you can click info.
Also what does the check box in the upper left doo? I don't see any change when toggled or not

**Comment by smallp** [comment]
The check box means if it should show collectors, which collect H2 in gas giant.
It will crash when you open the extension window while you remove a transfer station, and it will not show the building transfer station after opening the extension window. It cannot get the notify of building/undoing a built a transfer station, so it will crash. You can close the window before these operations done.
BTW, case insensitive will be done in next version.
